# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a11574affb1e51cbe9a9a52d73086b746185c7f5e00516e29f0abf67c44ba7dfeee5069ad1e3bf50c809675216da8069d2418bc3cafd937c74315f267868b593

test:
  secret_key_base: 56699127e2c9f1f4610225aff07b52ea836d9c754a994854ac94836a3b77bad4a76e56fc4577d6880ae457f0426747e9a3fac6f50e839178464e68b2bec3d633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
